# Start with the base image (for the server)

FROM python:alpine3.8

LABEL maintainer="alshapton@gmail.com"
LABEL version="0.1.4"

RUN apk update && \
    apk add nano vim && \
    pip install --upgrade pip 
    
COPY . /app

WORKDIR /app

# Update the base image, install dependencies and create the aliases file

RUN pip install -r requirements.txt && \
    python setup.py install 


# Open port 5000
EXPOSE 5000
# Need to change this port

# Start the API server



ENTRYPOINT ["sh","/app/start-kbAPI.ash"]

WORKDIR /data