#!/bin/sh

# Stop the build if there are Python syntax errors or undefined names
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
status=$?

if [ $status == 0 ]
then
    echo "Flake8(1) successful" 
else
    echo "Errors with flake8(1)" 
    exit 1
fi

flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
status=$?
if [ $status == 0 ]
then
    echo "Flake8(2) successful" 
else
    echo "Errors with flake8(2)" 
    exit 1
fi

# Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
codespell . --skip="*.drawio,./.git,*postman*" --ignore-words-list=hist --quiet-level=2
status=$?
if [ $status == 0 ]
then
    echo "Spelling check successful" 
else
    echo "Errors with spelling check" 
    exit 1
fi
