FROM python:alpine3.8

RUN apk update
RUN apk add nano vim

COPY . /app

WORKDIR /app
RUN pip install --upgrade pip 

RUN pip install -r requirements.txt && \ 
    python setup.py install && \
    cat /app/docker/aliases >> ~/.bashrc

WORKDIR /data
